tasks:
  hello-job:
    runner: razorci/openjdk:11-buster
    steps:
   
    - checkout    
    - commands:
      - |
         mvn sonar:sonar \
         -Dsonar.projectKey=razorop-app\
         -Dsonar.host.url=http://43.204.148.218:9000\
         -Dsonar.login=${TOKEN}
